# Generated by Django 4.1.7 on 2023-04-02 15:31

from django.db import migrations, models
import user_details.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_alter_user_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=user_details.models.generate_unique_token, max_length=8),
        ),
    ]
