# Generated by Django 4.1.7 on 2023-04-03 08:20

from django.db import migrations, models
import user_details.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=user_details.models.generate_unique_token, max_length=8, unique=True),
        ),
    ]
