# Generated by Django 4.1.7 on 2023-04-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_alter_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='place_specialitity',
            new_name='place_speciality',
        ),
    ]
