# Generated by Django 4.1.7 on 2023-04-03 11:07

from django.db import migrations, models
import user_details.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0006_rename_place_specialitity_user_place_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=user_details.models.generate_unique_token, max_length=8),
        ),
    ]
