# Generated by Django 4.1.7 on 2023-04-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userdet_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
