# Generated by Django 4.1.7 on 2023-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_userdet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdet',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
